import tkinter as tk
from tkinter import messagebox, ttk
import difflib

# List of movies with attributes
movies_data = {
       'Avatar': {'genres': 'Action, Adventure, Fantasy'},
    'Titanic': {'genres': 'Drama, Romance'},
    'Avengers: Endgame': {'genres': 'Action, Adventure, Drama'},
    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},
    'Frozen II': {'genres': 'Animation, Adventure, Comedy'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},

    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'The Dark Knight': {'genres': 'Action, Crime, Drama'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Pirates of the Caribbean: On Stranger Tides': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Lion King': {'genres': 'Animation, Adventure, Drama'},
    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Avengers: Age of Ultron': {'genres': 'Action, Adventure, Sci-Fi'},
    'Frozen': {'genres': 'Animation, Adventure, Comedy'},
    'Beauty and the Beast': {'genres': 'Animation, Family, Fantasy'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Alice in Wonderland': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast': {'genres': 'Family, Fantasy, Musical'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},

}

# Add more movies and genres
additional_movies = {
     'Avatar': {'genres': 'Action, Adventure, Fantasy'},
    'Titanic': {'genres': 'Drama, Romance'},
    'Avengers: Endgame': {'genres': 'Action, Adventure, Drama'},
    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},
    'Frozen II': {'genres': 'Animation, Adventure, Comedy'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'The Dark Knight': {'genres': 'Action, Crime, Drama'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Pirates of the Caribbean: On Stranger Tides': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Lion King': {'genres': 'Animation, Adventure, Drama'},
    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Avengers: Age of Ultron': {'genres': 'Action, Adventure, Sci-Fi'},
    'Frozen': {'genres': 'Animation, Adventure, Comedy'},
    'Beauty and the Beast': {'genres': 'Animation, Family, Fantasy'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Alice in Wonderland': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast': {'genres': 'Family, Fantasy, Musical'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},
    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},
    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},
    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},
    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},
    'Harry Potter and the Philosopher\'s Stone': {'genres': 'Adventure, Family, Fantasy'},
    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},
    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},
    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},
    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},
    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},
    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},
    'Minions': {'genres': 'Animation, Adventure, Comedy'},
    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},
    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},
    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},
    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},
    'Skyfall': {'genres': 'Action, Adventure, Thriller'},
    'The Dark Knight Rises': {'genres': 'Action, Thriller'},
    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},
    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},
    'Pirates of the Caribbean: Dead Man\'s Chest': {'genres': 'Action, Adventure, Fantasy'},
    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},
    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},
    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},
    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},
    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},
    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},
    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},
    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},
    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},

}

movies_data.update(additional_movies)

class MovieSearchApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Movie Search")
        self.root.geometry("700x500")
        self.root.configure(bg='#2e3f4f')

        # Style configuration for ttk widgets
        style = ttk.Style()
        style.configure('TButton', font=('Arial', 16), padding=10)
        style.configure('TLabel', font=('Arial', 14), background='#2e3f4f', foreground='white')
        style.configure('TEntry', font=('Arial', 16), padding=5)
        style.configure('TListbox', font=('Arial', 14), padding=5)

        # Header
        header = ttk.Label(root, text="Movie Search Engine(Beso)", font=('Arial', 24, 'bold'))
        header.pack(pady=20)

        # Search Entry Frame
        search_frame = ttk.Frame(root, padding=10)
        search_frame.pack(pady=10)

        # Search Entry
        self.search_var = tk.StringVar()
        search_entry = ttk.Entry(search_frame, textvariable=self.search_var, width=30)
        search_entry.grid(row=0, column=0, padx=10)

        # Search Button
        search_button = ttk.Button(search_frame, text="Search", command=self.search_movie)
        search_button.grid(row=0, column=1, padx=10)

        # Progress Bar
        self.progress = ttk.Progressbar(root, orient='horizontal', mode='determinate', length=400)
        self.progress.pack(pady=10)

        # Result Listbox
        self.result_listbox = tk.Listbox(root, font=('Arial', 14), width=40, height=10, bg='#f0f0f0')
        self.result_listbox.pack(pady=10)
        self.result_listbox.bind('<<ListboxSelect>>', self.show_movie_details)

        # Movie Details Label
        self.details_label = ttk.Label(root, text="")
        self.details_label.pack(pady=20)

    def search_movie(self):
        search_term = self.search_var.get()
        self.progress.start()
        close_matches = difflib.get_close_matches(search_term, movies_data.keys(), n=10, cutoff=0.1)
        self.progress.stop()

        self.result_listbox.delete(0, tk.END)
        for movie in close_matches:
            self.result_listbox.insert(tk.END, movie)

        if not close_matches:
            messagebox.showinfo("No Match Found", "No movies matched your search criteria.")

    def show_movie_details(self, event):
        selected_movie = self.result_listbox.get(self.result_listbox.curselection())
        details = movies_data[selected_movie]
        details_text = f"Title: {selected_movie}\nGenres: {details['genres']}"
        self.details_label.config(text=details_text)

if __name__ == "__main__":
    root = tk.Tk()
    app = MovieSearchApp(root)
    root.mainloop()